 * Serving Flask app 'main'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5006
Press CTRL+C to quit
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: 101-897-523
127.0.0.1 - - [30/Jan/2024 23:43:54] "GET /post/ HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2024 23:43:55] "GET /static/css/font-awesome.min.css HTTP/1.1" 404 -
127.0.0.1 - - [30/Jan/2024 23:43:55] "GET /static/css/style2.css HTTP/1.1" 304 -
127.0.0.1 - - [30/Jan/2024 23:43:56] "GET /static/imgs/transparent_image.png HTTP/1.1" 304 -
127.0.0.1 - - [30/Jan/2024 23:45:57] "POST /post/ HTTP/1.1" 302 -
127.0.0.1 - - [30/Jan/2024 23:45:58] "GET /post/ HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2024 23:45:58] "GET /static/css/style2.css HTTP/1.1" 304 -
127.0.0.1 - - [30/Jan/2024 23:45:58] "GET /static/css/font-awesome.min.css HTTP/1.1" 404 -
127.0.0.1 - - [30/Jan/2024 23:45:59] "GET /static/imgs/transparent_image.png HTTP/1.1" 304 -
 * Detected change in '/var/www/don/don/main.py', reloading
 * Detected change in '/var/www/don/don/main.py', reloading
 * Detected change in '/var/www/don/don/main.py', reloading
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: 101-897-523
 * Detected change in '/var/www/don/don/main.py', reloading
 * Detected change in '/var/www/don/don/main.py', reloading
 * Detected change in '/var/www/don/don/main.py', reloading
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: 101-897-523
 * Detected change in '/var/www/don/don/main.py', reloading
 * Detected change in '/var/www/don/don/main.py', reloading
 * Detected change in '/var/www/don/don/main.py', reloading
 * Detected change in '/var/www/don/don/main.py', reloading
 * Detected change in '/var/www/don/don/main.py', reloading
 * Detected change in '/var/www/don/don/main.py', reloading
 * Detected change in '/var/www/don/don/main.py', reloading
 * Detected change in '/var/www/don/don/main.py', reloading
 * Detected change in '/var/www/don/don/main.py', reloading
 * Detected change in '/var/www/don/don/main.py', reloading
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: 101-897-523
 * Detected change in '/usr/local/lib/python3.10/dist-packages/cv2/__init__.py', reloading
 * Detected change in '/usr/local/lib/python3.10/dist-packages/cv2/__init__.py', reloading
 * Detected change in '/usr/local/lib/python3.10/dist-packages/cv2/__init__.py', reloading
 * Detected change in '/usr/local/lib/python3.10/dist-packages/cv2/load_config_py2.py', reloading
 * Detected change in '/usr/local/lib/python3.10/dist-packages/cv2/load_config_py2.py', reloading
 * Detected change in '/usr/local/lib/python3.10/dist-packages/cv2/load_config_py2.py', reloading
 * Detected change in '/usr/local/lib/python3.10/dist-packages/cv2/load_config_py3.py', reloading
 * Detected change in '/usr/local/lib/python3.10/dist-packages/cv2/load_config_py3.py', reloading
 * Detected change in '/usr/local/lib/python3.10/dist-packages/cv2/load_config_py3.py', reloading
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: 101-897-523
 * Detected change in '/var/www/don/don/main.py', reloading
 * Detected change in '/var/www/don/don/main.py', reloading
 * Detected change in '/var/www/don/don/main.py', reloading
 * Restarting with watchdog (inotify)
Traceback (most recent call last):
  File "/var/www/don/don/main.py", line 56, in <module>
    import cv2
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
